site_name: Endades Newsletter

plugins:
  - i18n:
      default_language: es
      docs_structure: folder
      languages:
        - locale: es
          name: Español
          default: true
          build: true
        - locale: en
          name: English
          build: true

theme:
  name: material
  language: es 

extra_css:
  - stylesheets/custom.css

extra:
  alternate:
    - name: Español
      link: /
      lang: es
    - name: English
      link: /en/
      lang: en

nav:
  - index.md
  - MSI_Versions.md
