site_name: Endades Newsletter

plugins:
  - i18n:
      default_language: es
      docs_structure: folder
      languages:
        - locale: es
          name: Español
          default: true
          build: true
        - locale: en
          name: English
          build: true

theme:
  name: readthedocs
  highlightjs: true
  custom_dir: overrides

  
extra_javascript:
  - js/lang-switcher.js

extra_css:
  - stylesheets/custom.css

extra:
  hide:
    github: true
    edit_page: true


copyright: " "

nav:
  - index.md
  - MSI_Versions.md
